### ISSUE TITLE
[BOT-API] Get Order details

### ISSUE THREAD

**Issue by 4TT1L4** [geniusyield/dex-contracts-api#56]
**Problem:**
- The order details are available via a `POST` request that is sent to the `/orders/details` endpoint. This is very unusual. Our RESTful API should comply with the usual REST practices and we should respect the "principle of least astonishment".
- The semantics of the `POST` HTTP verb is to create resources. The `GET` verb should be used to retrieve data.

**Solution;**
- Change the API to use a `GET` request to load the order details.
- Remove the `details` suffix and use the nft_id from the URL instead of the request body/payload.

**Proposal:**
- Use the typical RESTful API design and accept a `GET` request sent to the `/orders/{nft_id}` endpoint.

**Comment by sourabhxyz** [comment]
> This is very unusual.

I don't think it's unusual. POST was chosen to support sending multiple nft tokens in request body, similar to https://docs.gomaestro.org/Indexer-API/Addresses/utxos-by-addresses.

I would suggest another endpoint GET `orders/details/{nft_identifier}`.

**Comment by sourabhxyz** [comment]
I have added GET variant with `details` path to maintain consistency with other variant in [this](https://github.com/geniusyield/dex-contracts-api/pull/60) PR. Let's avoid debating over "details" subpath.
